# Metadata for GitHub Actions marketplace
name: 'Release from Changelog'
description: 'Copy changelog version summary and create a GitHub release'
author: 'Alex Dombroski'

# Branding for marketplace
branding:
  icon: 'tag'
  color: 'blue'

# Inputs for the action
inputs:
  changelog-path:
    description: 'Path to the changelog file'
    required: false
    default: 'CHANGELOG.md'
  github-token:
    description: 'GitHub token for creating releases'
    required: true
  attachment-path:
    description: 'File to attach to the release'
    required: false

# Action runtime configuration
runs:
  using: "composite"
  env:
    GITHUB_TOKEN: $INPUT_GITHUB_TOKEN
    CHANGELOG_PATH: $INPUT_CHANGELOG_PATH
    ATTACHMENT_PATH: $INPUT_ATTACHMENT_PATH

  steps:
    - name: Check for Changelog
      run: |
        if [ ! -f "$CHANGELOG_PATH" ]; then
          echo "$CHANGELOG_PATH not found in $(pwd)"
          exit 1
        fi

    - name: Create GitHub Release
      id: create_release
      run: |
        # Use awk to extract the relevant section
        awk '
          BEGIN { found=0; }
          /^## \['"${{ github.ref_name }}"'\]/ { found=1; next; }
          /^## \[/ { if (found==1) exit; }
          { if (found==1) print; }
          END {
            if (found == 0) {
              print "No changelog entry found for tag " TAG > "/dev/stderr"
              exit 1
            }
          }
        ' $CHANGELOG_PATH > release_notes.txt

        TREE_LINK="[Tree](https://github.com/${{ github.repository }}/tree/${{ github.ref_name }})"
        COMMIT_LINK="[Commits](https://github.com/${{ github.repository }}/commits/${{ github.ref_name }})"

        if PREV_TAG=$(git describe --tags --abbrev=0 "${{ github.ref_name }}~1" 2>/dev/null); then
          COMPARE_LINK="[Compare](https://github.com/${{ github.repository }}/compare/${PREV_TAG}...${{ github.ref_name }})"
        else
          COMPARE_LINK=""
        fi

        CHANGELOG="See the full [changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)."
        RELEASE_BODY=$(printf "%s\n\n%s\n\n## GitHub Links\n\n%s - %s%s" "$(cat release_notes.txt)" "$CHANGELOG" "$TREE_LINK" "$COMMIT_LINK" "${COMPARE_LINK:+ - $COMPARE_LINK}")

        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "$RELEASE_BODY"

    - name: Upload Attachment
      if: env.ATTACHMENT_PATH
      run: |
        gh release upload ${{ github.ref_name }} $ATTACHMENT_PATH