# Metadata for GitHub Actions marketplace
name: 'Release from Changelog'
description: 'Read changelog content and create a GitHub release'
author: 'Alex Dombroski'

# Branding for marketplace
branding:
  icon: 'tag'
  color: 'blue'

# Inputs for the action
inputs:
  changelog-path:
    description: 'Path to the changelog file'
    required: false
    default: 'CHANGELOG.md'
  version-tag:
    description: 'Version tag to create release for (e.g., 1.0.0)'
    required: true
  github-token:
    description: 'GitHub token for creating releases'
    required: true
    default: ${{ github.token }}

# Outputs from the action
outputs:
  release-url:
    description: 'URL of the created release'
  release-body:
    description: 'Content extracted from changelog'

# Action runtime configuration
runs:
  using: "composite"
  steps:
    - name: Create GitHub Release
      id: create_release
      run: |
        curl -s https://raw.githubusercontent.com/${{ github.repository }}/main/CHANGELOG.md -o CHANGELOG.md  
        if [ $? -ne 0 ]; then
          echo "Failed to download CHANGELOG.md"
          exit 1
        fi

        # Use awk to extract the relevant section
        awk -v tag="${{ github.ref_name }}" '
          BEGIN { found=0; }
          /^## \['"${{ github.ref_name }}"'\]/ { found=1; next; }
          /^## \[/ { if (found==1) found=2; }
          { if (found==1) print; }
        ' CHANGELOG.md > release_notes.txt

        TREE_LINK="[Tree](https://github.com/${{ github.repository }}/tree/${{ github.ref_name }})"
        COMMIT_LINK="[Commits](https://github.com/${{ github.repository }}/commits/${{ github.ref_name }})"
        COMPARE_LINK="[Compare](https://github.com/${{ github.repository }}/compare/$(git describe --tags --abbrev=0 ${{ github.ref_name }}~1)...${{ github.ref_name }})"

        CHANGELOG="See the full [changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)."
        RELEASE_BODY=$(printf "%s\n\n%s\n\n## GitHub Links\n\n%s - %s - %s" "$(cat release_notes.txt)" "$CHANGELOG" "$TREE_LINK" "$COMMIT_LINK" "$COMPARE_LINK")

        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "$RELEASE_BODY"

        echo "RELEASE_ID=${{ github.ref_name }}" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload .vsix to release
      run: |
        gh release upload $RELEASE_ID $VSIX_PATH \
          --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete tag on publish prep failure
      if: failure()
      run: |
        TAG_REF=${GITHUB_REF#refs/tags/}
        git push origin :refs/tags/$TAG_REF --no-verify
        echo "Deployment failed. Deleted tag $TAG_REF"